// Generated by https://quicktype.io

export interface ClashResponse {
  tag: string;
  name: string;
  type: string;
  description: string;
  badgeId: number;
  clanScore: number;
  clanWarTrophies: number;
  location: Location;
  requiredTrophies: number;
  donationsPerWeek: number;
  clanChestStatus: string;
  clanChestLevel: number;
  clanChestMaxLevel: number;
  members: number;
  memberList: MemberList[];
}

export interface Location {
  id: number;
  name: string;
  isCountry: boolean;
}

export interface MemberList {
  tag: string;
  name: string;
  role: Role;
  lastSeen: string;
  expLevel: number;
  trophies: number;
  arena: Arena;
  clanRank: number;
  previousClanRank: number;
  donations: number;
  donationsReceived: number;
  clanChestPoints: number;
}

export interface Arena {
  id: number;
  name: Name;
}

export enum Name {
  ChallengerII = 'Challenger II',
  ChallengerIII = 'Challenger III',
  LegendaryArena = 'Legendary Arena',
  MasterI = 'Master I',
  MasterII = 'Master II',
}

export enum Role {
  CoLeader = 'coLeader',
  Elder = 'elder',
  Leader = 'leader',
  Member = 'member',
}
